version: '3.9'

networks:
  docker-network:
    name: docker-network
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432
    networks:
      - docker-network
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: on-failure
  nestjs:
    depends_on:
      - postgres
    container_name: nestjs
    build: ./nest-back
    ports:
      - 3000:3000
    networks:
      - docker-network
    env_file:
      - ./.env
    restart: on-failure
  sveltekit:
    depends_on:
      - nestjs
    container_name: sveltekit
    build:
      context: ./svelte-front
      args:
        - VITE_HOST=$VITE_HOST
        - VITE_NESTJS_PORT=$VITE_NESTJS_PORT
        - SVELTEKIT_PORT=$SVELTEKIT_PORT
    ports:
     - 5173:5173
    networks:
      - docker-network
    restart: on-failure
