version: '3.9'

networks:
  docker-network:
    name: docker-network
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
    ports:
      - 5432:5432
    networks:
      - docker-network
    restart: always
  nest:
    depends_on:
      - db
    container_name: backend
    build: ./nest-back
    ports:
      - 3000:3000
    networks:
      - docker-network
    env_file:
      - ./.env
    restart: always
  svelte:
    depends_on:
      - nest
    container_name: frontend
    build: ./svelte-front
    ports:
     - 5173:5173
    networks:
      - docker-network
    env_file:
      - ./.env
    restart: always
