version: '3.7'

services:

  database:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend/data/pg:/var/lib/postgresql/data
    entrypoint:
      [
        "bash",
        "-c",
        "echo '' > /var/lib/postgresql/data/.keep && rm /var/lib/postgresql/data/.keep && docker-entrypoint.sh postgres"
      ]
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
